apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: my-nginx-deployment # deployment.yaml에 적힌 metadata.name과 동일해야 합니다!
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
namePrefix: prod-