apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-my-sample-app-ingress
  annotations:
    # ALB 생성 설정
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # # HTTPS 설정 (자물쇠)
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:904053119728:certificate/9060b6e2-73dc-47c2-aa5c-5c4c4a0c6961 # <--- 여기에 복사한 ARN 붙여넣기
    
    # # HTTP -> HTTPS 자동 리다이렉트
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    
    # 건강 검진 경로 (기본설정)
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  rules:
    - host: www.niha5ma.store # 선생님의 도메인으로 고정
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-sample-app-svc
                port:
                  number: 80