apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-sample-app-ingress # 앞에 dev-는 ArgoCD가 자동으로 붙여줄 겁니다.
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ingress.class: alb
    # --- 여기서부터 HTTPS 핵심 설정 ---
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:904053119728:certificate/여기에_실제_ID_꼭_확인"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: www.niha5ma.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-sample-app-svc
                port:
                  number: 80