name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4 # 최신 Node.js 24 대응 버전으로 업그레이드

      - name: 2. Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::904053119728:role/GitHubActions-ECR-Role
          aws-region: ap-northeast-2

      - name: 3. Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-sample-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: 5. Update image tag in base/deployment.yaml
        run: |
          NEW_IMAGE="${{ steps.login-ecr.outputs.registry }}/my-sample-app:${{ github.sha }}"
          sed -i "s|IMAGE_PLACEHOLDER|$NEW_IMAGE|g" base/deployment.yaml
          
      - name: 6. Push changes to GitHub (Force)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git reset --soft origin/main
          git add base/deployment.yaml
          git commit -m "🚀 자동 업데이트: 이미지 태그 변경 (${{ github.sha }})" || echo "No changes"
          git push origin main --force

      - name: 7. Connect to EKS
        run: |
          # ⚠️ 여기에 진짜 EKS 클러스터 이름을 적으세요!
          aws eks update-kubeconfig --region ap-northeast-2 --name my-sample-eks
          
      - name: 8. Deploy to K8s
        run: |
          # kustomize를 이용해 overlays/dev 환경으로 배포합니다.
          kubectl apply -k overlays/dev